# Copyright 2026 BL Consulting
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).

import logging

from odoo import _, api, fields, models
from odoo.exceptions import UserError

_logger = logging.getLogger(__name__)


class MrpProduction(models.Model):
    """Adds a 'staging' gate to the MO lifecycle.

    Stage flow:
        intermediate (default on create)
            ├─ MO confirmed → production moves exist, forecast sees demand,
            │   raw moves bypass buffer locations (source = WH/Stock instead
            │   of pbm_loc_id), finished moves bypass sam_loc_id similarly.
            │   No Pick/Store pickings are generated by pull rules because
            │   there is no Stock↔buffer gap to fill.
            │
        prepared (user-triggered via action_prepare_production)
            ├─ Endpoints swap back to the buffers per warehouse manufacture_steps
            │   (pbm/pbm_sam). Moves re-confirmed → pull rules evaluate normally
            │   → Pick/Store pickings born via native procurement.
            ↓
        (MO continues с native progress → done flow; stage няма повече effect)

    Stage e ОРТОГОНАЛНО на native ``state`` (draft/confirmed/progress/done/cancel).
    Active windows: stage има смисъл само when ``state ∈ {confirmed, progress}``.
    Before confirm няма moves; after done няма какво да се подготвя.
    """

    _inherit = "mrp.production"

    stage = fields.Selection(
        [
            ("intermediate", "Intermediate"),
            ("prepared", "Prepared for Production"),
        ],
        string="Preparation Stage",
        default="intermediate",
        copy=False,
        index=True,
        tracking=True,
        help=(
            "Logistic gate between planning and materialisation of transfers. "
            "'Intermediate' = production moves exist (forecast active), но "
            "Pick/Store pickings не са родени. 'Prepared' = endpoints swap-нати "
            "към буферните локации, pull rules задействани, pickings родени."
        ),
    )

    staged_preparation_enabled = fields.Boolean(
        related="picking_type_id.staged_preparation_enabled",
        store=False,
        help="Mirror of the picking type's flag — drives override visibility.",
    )

    # ── Helpers ─────────────────────────────────────────────────────────

    def _staged_intermediate_active(self):
        """True когато тази MO трябва да bypass-не буферните локации."""
        self.ensure_one()
        return bool(
            self.staged_preparation_enabled and self.stage == "intermediate"
        )

    def _staged_warehouse(self):
        """Връща ``stock.warehouse`` от MO source location (нативно поле).
        Empty recordset ако location_src_id не сочи към warehouse."""
        self.ensure_one()
        wh = self.location_src_id.warehouse_id
        return wh or self.env["stock.warehouse"]

    # ── Override: move endpoint construction ────────────────────────────
    # Native (Odoo 18):
    #   raw move:      location_id = self.location_src_id  (= pbm_loc when 2/3-step)
    #                  location_dest_id = property_stock_production (Production)
    #   finished move: location_id = property_stock_production (Production)
    #                  location_dest_id = self.location_dest_id (= sam_loc when 3-step)
    # In intermediate stage we keep the Production endpoint (fixed axis) but
    # replace the OTHER side с warehouse.lot_stock_id (WH/Stock) — bypass-ва
    # буфера. Resulting move pair: Stock → Production → Stock, no Stock↔buffer
    # gap → pull rules не раждат Pick/Store.

    def _get_move_raw_values(self, product, product_uom_qty, product_uom,
                             operation_id=False, bom_line=False):
        vals = super()._get_move_raw_values(
            product, product_uom_qty, product_uom, operation_id, bom_line,
        )
        if not self._staged_intermediate_active():
            return vals
        wh = self._staged_warehouse()
        if wh and wh.lot_stock_id:
            vals["location_id"] = wh.lot_stock_id.id
            vals["warehouse_id"] = wh.id
        return vals

    def _get_move_finished_values(self, product_id, product_uom_qty, product_uom,
                                  operation_id=False, byproduct_id=False, cost_share=0):
        vals = super()._get_move_finished_values(
            product_id, product_uom_qty, product_uom,
            operation_id, byproduct_id, cost_share,
        )
        if not self._staged_intermediate_active():
            return vals
        wh = self._staged_warehouse()
        if wh and wh.lot_stock_id:
            vals["location_dest_id"] = wh.lot_stock_id.id
            vals["warehouse_id"] = wh.id
        return vals

    # ── Action: prepare for production (intermediate → prepared) ────────

    def action_prepare_production(self):
        """Transition stage to 'prepared': swap endpoints back to warehouse
        buffers per ``manufacture_steps``, re-trigger procurement so pull
        rules generate Pick/Store pickings natively.

        Idempotent guards:
        - Само за MO с stage='intermediate' и staged_preparation_enabled.
        - Само when state ∈ {confirmed, progress} (преди confirm няма moves;
          след done няма какво да се подготвя).
        - mrp_one_step warehouse → no-op логистично, само stage става prepared.
        """
        for production in self:
            production._action_prepare_production_one()
        return True

    def _action_prepare_production_one(self):
        self.ensure_one()
        if not self.staged_preparation_enabled:
            raise UserError(_(
                "Staged preparation is not enabled for this picking type. "
                "Enable 'Staged Preparation' on '%s' first.",
                self.picking_type_id.display_name,
            ))
        if self.stage != "intermediate":
            raise UserError(_(
                "MO %s is already in stage '%s'. Reverse transition is not "
                "supported in this version.",
                self.name, self.stage,
            ))
        if self.state not in ("confirmed", "progress"):
            raise UserError(_(
                "Preparation requires the MO to be in 'Confirmed' or "
                "'In Progress' state (current: '%s').",
                self.state,
            ))

        wh = self._staged_warehouse()
        if not wh:
            # Не би трябвало да се случи в healthy data; fail-safe — flip stage,
            # не пипай moves.
            _logger.warning(
                "MO %s has no warehouse on location_src_id; marking prepared "
                "without endpoint swap.", self.name,
            )
            self.stage = "prepared"
            return

        # Determine target endpoint locations per warehouse step config.
        # mrp_one_step: nothing to do logistically — pull rules стартират на
        # confirm so there's no "buffer" gap.
        target_raw_src = None       # only set when warehouse е 2/3-step
        target_finished_dest = None  # only set when warehouse е 3-step
        steps = wh.manufacture_steps
        if steps == "pbm":
            target_raw_src = wh.pbm_loc_id
        elif steps == "pbm_sam":
            target_raw_src = wh.pbm_loc_id
            target_finished_dest = wh.sam_loc_id

        # Ensure procurement_group_id за MO-то, иначе новородените Pick/Store
        # се merge-ват с други MO-та (merge ключът включва group_id).
        if not self.procurement_group_id:
            self.procurement_group_id = self.env["procurement.group"].create({
                "name": self.name,
                "move_type": self.move_type or "direct",
                "partner_id": self.partner_id.id if self.partner_id else False,
            })

        moves_to_reconfirm = self.env["stock.move"]

        # ── Swap raw move sources (only when target_raw_src е set) ──────
        if target_raw_src:
            raw_moves = self.move_raw_ids.filtered(
                lambda m: m.state not in ("done", "cancel")
            )
            for move in raw_moves:
                if move.location_id == target_raw_src:
                    continue
                if move.state == "assigned":
                    move._do_unreserve()
                move.write({
                    "location_id": target_raw_src.id,
                    "group_id": self.procurement_group_id.id,
                })
                moves_to_reconfirm |= move

        # ── Swap finished move dest (only when target_finished_dest е set) ──
        if target_finished_dest:
            finished_moves = self.move_finished_ids.filtered(
                lambda m: m.state not in ("done", "cancel")
            )
            for move in finished_moves:
                if move.location_dest_id == target_finished_dest:
                    continue
                if move.state == "assigned":
                    move._do_unreserve()
                move.write({
                    "location_dest_id": target_finished_dest.id,
                    "group_id": self.procurement_group_id.id,
                })
                moves_to_reconfirm |= move

        # ── Re-trigger pull rules чрез _action_confirm ──────────────────
        # merge=False — не искаме новородените Pick/Store да се merge-нат с
        # други MO's pickings (procurement_group_id вече осигурява separation,
        # но изричен merge=False е допълнителна гаранция).
        if moves_to_reconfirm:
            moves_to_reconfirm._action_confirm(merge=False)
            _logger.info(
                "Staged preparation: MO %s → %d moves re-confirmed (steps=%s)",
                self.name, len(moves_to_reconfirm), steps,
            )

        self.stage = "prepared"

    # ── Suppress native procurement on intermediate confirm ─────────────
    # Native confirm на mrp.production триггерира procurement за raw moves
    # автоматично. При intermediate stage искаме това поведение да е no-op
    # (защото endpoint-ите вече сочат към Stock, не към buffer — pull rules
    # няма да родят нищо). Не override-ваме action_confirm, оставяме нативния
    # flow да върви; интересен side-effect: moves с location_id=Stock се
    # opt-in за внутрешен Pick edge case, но pull rules за Stock→Stock не
    # съществуват → no pickings born. ✓
